version: "3"

services:
  php:
    image: previousnext/php-apache:7.2-3.x-dev
    # This makes the container run on the same network stack as your
    # workstation. Meaning that you can interact on "localhost".
    network_mode: host
    volumes:
      - .:/data
    environment:
      - SIMPLETEST_BASE_URL=http://127.0.0.1
      - SIMPLETEST_DB=mysql://root:root@127.0.0.1/d8_testing
      - BROWSERTEST_OUTPUT_DIRECTORY=/data/app/sites/simpletest/browser_output

  db:
    image: mariadb
    network_mode: host
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=local
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal

  mail:
    image: mailhog/mailhog
    network_mode: host
