version: "3"

services:
  app:
    image: previousnext/php-apache:7.2-3.x-dev
    # You will notice that we are forwarding port which do not belong to PHP.
    # We have to declare them here because these "sidecar" services are sharing
    # THIS containers network stack.
    ports:
      - "80:80"
      - "3306:3306"
      - "8983:8983"
      - "8025:8025"
      - "8910:8910"
    volumes:
      - .:/data:cached
    environment:
      - SIMPLETEST_BASE_URL=http://127.0.0.1
      - SIMPLETEST_DB=mysql://root:root@127.0.0.1/d8_testing
      - BROWSERTEST_OUTPUT_DIRECTORY=/data/app/sites/simpletest/browser_output
      - MINK_DRIVER_ARGS_WEBDRIVER=["chrome", {"browserName":"chrome","chromeOptions":{"args":["--disable-gpu","--headless"]}}, "http://localhost:9515"]

  xdebug:
    image: nickschuch/d4m-tcp-forwarder
    network_mode: host
    environment:
      - PORT=9000

  db:
    image: mariadb
    network_mode: service:app
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=local
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal

  mail:
    image: mailhog/mailhog
    network_mode: service:app
